/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#859988',
        'on-surface-variant': '#c2c8bf',
        'outline-variant': '#424841',
        'surface-variant': '#333533',
        tertiary: '#b7ccb9',
        'surface-container': '#1e201e',
        outline: '#8c938a',
        'on-error': '#690005',
        'on-tertiary': '#233427',
        'primary-fixed': '#c5edc5',
        'secondary-fixed': '#ffdcbd',
        'on-tertiary-fixed-variant': '#394b3d',
        'surface-container-high': '#292a28',
        'on-error-container': '#ffdad6',
        'on-tertiary-fixed': '#0e1f13',
        'tertiary-fixed': '#d3e8d5',
        'surface-container-low': '#1a1c1a',
        'secondary-container': '#65411a',
        background: '#121412',
        'on-tertiary-container': '#1f3124',
        'surface-container-highest': '#333533',
        'on-surface': '#e2e3df',
        'tertiary-fixed-dim': '#b7ccb9',
        'on-secondary-container': '#e1af7e',
        'surface-bright': '#383a37',
        'secondary-fixed-dim': '#f0bd8b',
        'surface-dim': '#121412',
        'inverse-on-surface': '#2f312e',
        error: '#ffb4ab',
        'on-secondary-fixed-variant': '#623f18',
        'surface-tint': '#a9d0aa',
        'surface-container-lowest': '#0d0f0d',
        'on-secondary-fixed': '#2c1600',
        'inverse-primary': '#446647',
        'on-primary-container': '#113319',
        primary: '#a9d0aa',
        'on-background': '#e2e3df',
        'on-primary-fixed-variant': '#2c4e31',
        'inverse-surface': '#e2e3df',
        'primary-container': '#789d7a',
        'on-primary': '#15371c',
        surface: '#121412',
        'on-secondary': '#482904',
        'primary-fixed-dim': '#a9d0aa',
        secondary: '#f0bd8b',
        'error-container': '#93000a',
        'on-primary-fixed': '#002109',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '48px',
        'container-max': '1280px',
        'margin-mobile': '16px',
        unit: '8px',
        gutter: '24px',
      },
      fontFamily: {
        'headline-md': ['Nunito Sans', 'sans-serif'],
        'headline-lg-mobile': ['Nunito Sans', 'sans-serif'],
        'body-md': ['Nunito Sans', 'sans-serif'],
        'body-lg': ['Nunito Sans', 'sans-serif'],
        'display-lg': ['Nunito Sans', 'sans-serif'],
        'headline-lg': ['Nunito Sans', 'sans-serif'],
        'label-md': ['Nunito Sans', 'sans-serif'],
        'label-sm': ['Nunito Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': [
          '48px',
          { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' },
        ],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'label-md': [
          '14px',
          { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' },
        ],
        'label-sm': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '700' },
        ],
      },
    },
  },
  plugins: [],
}
